spring:
  webflux:
    hiddenmethod:
      filter:
        enabled: true
  devtools:
    restart:
      log-condition-evaluation-delta: true

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG
