spring:
  webflux:
    hiddenmethod:
      filter:
        enabled: true

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG
